#! /bin/sh

logfile="$HOME/.Space2Ctrl.log"

start() {
	# Map Caps_Lock to Escape
	xmodmap -e "remove Lock = Caps_Lock"
	xmodmap -e "keysym Caps_Lock = Escape"
	xmodmap -e "add Lock = Caps_Lock"

	# For remapping the "'" key to ctrl
	origmap=$(xmodmap -pke | grep -E "^keycode[[:blank:]]*?48")
	newmap=$(echo ${origmap} | perl -pe "s/ apostrophe/ Control_L/g")
	newmap=$(echo ${newmap} | perl -pe "s/ quotedbl/ NoSymbol/g")
	xmodmap -e "$newmap"
	xmodmap -e "keycode 255 = apostrophe quotedbl apostrophe quotedbl"

	# For remapping the caps lock key to ctrl
	origmap=$(xmodmap -pke | grep -E "^keycode[[:blank:]]*?66")
	newmap=$(echo ${origmap} | perl -pe "s/ Escape/ Control_L/g")
	xmodmap -e "$newmap"
	xmodmap -e "keycode 254 = Escape NoSymbol Escape"

	nohup "${0%/*}/s2c" >> "$logfile" 2>&1 &
	sleep 1 # Don't ask me why but we need to wait more than one second else the ctrl modifier is
		# reinitialized to XK_Control_L XK_Control_R as soon as keycode 48 is pressed!
	`xmodmap -e "add control = Control_L Control_R"`

	echo "Space2Ctrl is now active (logfile: $logfile)"
	exit 0
}

stop() {
	setxkbmap us # Reset xmodmap settings.. kind of a hack :3

	if pgrep -x s2c
	then
		kill -s TERM `pgrep -x s2c` 2>&1
	fi
}

restart() {
	stop
	sleep 1 # sanity
	start
}

case $1 in
	start)
		echo "Starting Space2Ctrl..."
		start;;
	stop)
		echo "Stopping Space2Ctrl..."
		stop;;
	restart)
		echo "Restarting Space2Ctrl..."
		restart;;
	*)
		echo "Please pass start or stop";;
esac
